#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
echo "Running ctags on $dir"
trap 'rm -f "$dir/$$.tags"' EXIT
ctags -R --fields=+l --languages=python --python-kinds=-iv --exclude=.git -f"$dir/$$.tags" $(python -c "import os, sys; print(' '.join('{}'.format(d) for d in sys.path if os.path.isdir(d)))")
mv "$dir/$$.tags" "$dir/pythonlib_tags"
