#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
ctags -R --tag-relative --fields=+l --languages=python,javascript --python-kinds=-iv --exclude=*static_files* --exclude=*node_modules* --exclude=*.git* -f"$dir/$$.tags" .
mv "$dir/$$.tags" "$dir/project_ctags"
