set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'terryma/vim-multiple-cursors'
" Plugin 'valloric/youcompleteme'

" Nodejs Plugins
Plugin 'moll/vim-node'

call vundle#end()
filetype plugin indent on

" Vim-airline
set t_Co=256
set laststatus=2
let g:airline_theme = 'murmur'

syntax on
set autoindent
set history=1000

" toggle between modes almost instantly
set ttimeoutlen=0

" update file edited outside vim
set autoread

" Show white line in cursor
set cursorline

" set the terminal title to the current file
set title

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

"Lowercase = case insensitive, any uppercase = case sensitive:
set smartcase

" Highlight search results:
set hlsearch
hi Search cterm=NONE ctermfg=grey ctermbg=blue

" Remove highlighted results with F3
nnoremap <F3> :set hlsearch!<CR>

" show search results as you type
set incsearch

" Show matching brackets when text indicator is over them:
set showmatch

" Set utf8 as standard encoding and en_US as the standard language:
set encoding=utf8

" Enable mouse:
set mouse=a

" No annoying sound on errors
set noerrorbells
set novisualbell
set tm=500

" Autoreload .vimrc on save
augroup AutoReloadVimRC
	au!
	" automatically reload vimrc when it's saved
	au BufWritePost $MYVIMRC so $MYVIMRC
augroup END

" Show line number
if version >= 703
	set number          " show absolute line number for the current line
	set relativenumber  " show line number relative to current position
else
	set number
endif

" Jump to last position on re-open
au BufReadPost * if &ft != "gitcommit" && line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif

